### ISSUE TITLE
api_key generation salt disclosed

### ISSUE THREAD

**Issue by fulmicoton** [LinkedInAttic/indextank-service#1]
I think your api_key generation salt should be within a config file. If ids get public, I think a bruteforce attack might be possible.

I didn't have time to study more the code, so I'm sorry if I got something wrong here.

**Comment by jhandl** [comment]
Thanks for catching that. Api keys include a random part, but you're right that the salt should not be public.

**Comment by fulmicoton** [comment]
1.000.000 seems a bit small to me. Do you have some kind of throttling on authentication failure?

**Comment by jhandl** [comment]
You're right, I'm changing that too. Thanks!

**Comment by fulmicoton** [comment]
Awesome thanks for the fast commit!
